/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Comment, Player } from "./components/player-detail/player-detail";
export { Comment, Player } from "./components/player-detail/player-detail";
export namespace Components {
    interface PlayerDetail {
        /**
          * @default false
         */
        "commentLoading": boolean;
        /**
          * @default []
         */
        "comments": Comment[];
        /**
          * @default ''
         */
        "error": string;
        /**
          * @default false
         */
        "isAdmin": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        "player"?: Player | null;
    }
}
export interface PlayerDetailCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPlayerDetailElement;
}
declare global {
    interface HTMLPlayerDetailElementEventMap {
        "addComment": {
    author: string;
    text: string;
    rating: number;
    location?: { lat: number; lng: number };
  };
        "deleteComment": string;
    }
    interface HTMLPlayerDetailElement extends Components.PlayerDetail, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPlayerDetailElementEventMap>(type: K, listener: (this: HTMLPlayerDetailElement, ev: PlayerDetailCustomEvent<HTMLPlayerDetailElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPlayerDetailElementEventMap>(type: K, listener: (this: HTMLPlayerDetailElement, ev: PlayerDetailCustomEvent<HTMLPlayerDetailElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPlayerDetailElement: {
        prototype: HTMLPlayerDetailElement;
        new (): HTMLPlayerDetailElement;
    };
    interface HTMLElementTagNameMap {
        "player-detail": HTMLPlayerDetailElement;
    }
}
declare namespace LocalJSX {
    interface PlayerDetail {
        /**
          * @default false
         */
        "commentLoading"?: boolean;
        /**
          * @default []
         */
        "comments"?: Comment[];
        /**
          * @default ''
         */
        "error"?: string;
        /**
          * @default false
         */
        "isAdmin"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        "onAddComment"?: (event: PlayerDetailCustomEvent<{
    author: string;
    text: string;
    rating: number;
    location?: { lat: number; lng: number };
  }>) => void;
        "onDeleteComment"?: (event: PlayerDetailCustomEvent<string>) => void;
        "player"?: Player | null;
    }

    interface PlayerDetailAttributes {
        "isAdmin": boolean;
        "loading": boolean;
        "commentLoading": boolean;
        "error": string;
    }

    interface IntrinsicElements {
        "player-detail": Omit<PlayerDetail, keyof PlayerDetailAttributes> & { [K in keyof PlayerDetail & keyof PlayerDetailAttributes]?: PlayerDetail[K] } & { [K in keyof PlayerDetail & keyof PlayerDetailAttributes as `attr:${K}`]?: PlayerDetailAttributes[K] } & { [K in keyof PlayerDetail & keyof PlayerDetailAttributes as `prop:${K}`]?: PlayerDetail[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "player-detail": LocalJSX.IntrinsicElements["player-detail"] & JSXBase.HTMLAttributes<HTMLPlayerDetailElement>;
        }
    }
}
