spring:
  application:
    name: comment-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:config-server}:8888
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://mi-base-datos:5432/db_sistema}
    username: ${DB_USERNAME:usuario_futbol}
    password: ${DB_PASSWORD:password_seguro123}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8082}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://service-registry:8761/eureka/}

firebase:
  service-account-base64: ${FIREBASE_SERVICE_ACCOUNT_B64:}
