spring:
  application:
    name: comment-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:config-server}:8888
  datasource:
    driver-class-name: org.postgresql.Driver

server:
  port: ${PORT:8082}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://service-registry:8761/eureka/}

firebase:
  service-account-base64: ${FIREBASE_SERVICE_ACCOUNT_B64:}
